### ISSUE TITLE
Groups workflow

### ISSUE THREAD

**Issue by hhkaos** [flavors/arcgis-marketplace#14]
Testing
https://hhkaos.github.io/domake-front-test/product/setup/?id=54d387d3be3d41c882a94075003ae420

**Comment by mongkok** [comment]
* Create item
* Create a group (if not exists).
* Assign item to group
* Configure group to org defaults

**Comment by hhkaos** [comment]
<img width="1055" alt="screen shot 2017-06-17 at 00 19 09" src="https://user-images.githubusercontent.com/826965/27246558-b766b56c-52f2-11e7-8ee5-a24916b4535a.png">
